---
abstract: 'Verify that all the modules in a distribution have the same version number.'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Carp: 0
  Test::Builder::Tester: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Dist-VersionSync
provides:
  Test::Dist::VersionSync:
    file: lib/Test/Dist/VersionSync.pm
    version: v1.0.4
requires:
  Data::Dumper: 0
  Test::More: 0.94
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=test-dist-versionsync
  homepage: https://metacpan.org/release/Test-Dist-VersionSync
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: https://github.com/guillaumeaubert/Test-Dist-VersionSync
version: v1.0.4
