---
abstract: 'Verify that all the modules in a distribution have the same version number.'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Carp: 0
  Data::Dumper: 0
  Test::Builder::Tester: 0
  Test::More: 0.94
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Dist-VersionSync
provides:
  Test::Dist::VersionSync:
    file: lib/Test/Dist/VersionSync.pm
    version: v1.0.2
requires:
  perl: 5.006
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: v1.0.2
