---
abstract: 'Verify that all the modules in a distribution have the same version number.'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Carp: '0'
  Test::Builder::Tester: '0'
  Test::FailWarnings: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Dist-VersionSync
no_index:
  namespace:
    - TestModule1
    - TestModule2
provides:
  Test::Dist::VersionSync:
    file: lib/Test/Dist/VersionSync.pm
    version: v1.1.3
requires:
  Data::Dumper: '0'
  Test::More: '0.94'
  perl: '5.006'
resources:
  bugtracker: https://github.com/guillaumeaubert/Test-Dist-VersionSync/issues
  homepage: https://metacpan.org/release/Test-Dist-VersionSync
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: https://github.com/guillaumeaubert/Test-Dist-VersionSync
version: v1.1.3
